Repository rinnakk/CustomerServiceDigital, pull requests merged in 2023-08, with the labels that each got.

#2 add csd st code.
  src/flows/CustomerServicesDigital-ServicesAndTicketing.json
Labels: No Changes

#3 fix small bug (sorry)
  src/flows/CustomerServicesDigital-ServicesAndTicketing.json
Labels: Extra Small

#1 add csd la code.
  src/flows/CustomerServiceDigital-LeadAutomation.json
Labels: No Changes

#4 Add structure, documentation
  README.md
  src/LeadAutomation/.node-red/environment.example
  src/LeadAutomation/.node-red/package.json
  src/LeadAutomation/flows.json
  src/LeadAutomation/settings.js
  src/ServicesAndTicketing/.node-red/environment.example
  src/ServicesAndTicketing/.node-red/package.json
  src/ServicesAndTicketing/flows.json
  src/ServicesAndTicketing/settings.js
Labels: Extra Large
